version: "3.8"
services:
  database:
    platform: linux/x86_64
    image: mysql:8.0.19
    container_name: agrologisticsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: payday2020
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: agrologisticsdb
    volumes:
      - agrovol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5


  agro-logistics:
    platform: linux/x86_64
    image: richieoscar/agrologistics:lts
    restart: always

    depends_on:
      database:
        condition: service_healthy
    ports:
      - "9080"
    environment:
      MYSQL_ROOT_PASSWORD: payday2020
      MYSQL_ROOT_USER: root
      MYSQL_HOST: agrologisticsdb
      MYSQL_PORT: 3306

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - agro-logistics
    ports:
      - "4000:4000"


networks:
  default:
    name: agro-network

volumes:
  agrovol:
